services:
  - name: mongo:latest
    alias: mongo
  - name: rabbitmq:management
    alias: rabbitmq

stages:
  - test
  - publish
  - release

variables:
  SBT_OPTS: "-Dsbt.global.base=sbt-cache/.sbtboot -Dsbt.boot.directory=sbt-cache/.boot -Dsbt.ivy.home=sbt-cache/.ivy"
  MONGO_INITDB_ROOT_USERNAME: admin
  MONGO_INITDB_ROOT_PASSWORD: admin
  RABBITMQ_DEFAULT_USER: guest
  RABBITMQ_DEFAULT_PASS: guest

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  untracked: false
  paths:
    - "sbt-cache/.ivy/cache"
    - "sbt-cache/.boot"
    - "sbt-cache/.sbtboot"
    - "sbt-cache/target"

test:
  stage: test
  image: openjdk:14-slim
  tags:
    - wopr
  variables:
    MONGO_HOST: mongo
    MONGO_DATABASE: prefetch-test
    MONGO_COLLECTION: documents
    MONGO_USERNAME: admin
    MONGO_PASSWORD: admin
    RABBITMQ_HOST: rabbitmq
    RABBITMQ_USERNAME: guest
    RABBITMQ_PASSWORD: guest
  before_script:
    - apt-get update -yqq
    - apt-get install -yqq apt-transport-https ca-certificates gnupg
    - echo "deb https://dl.bintray.com/sbt/debian /" | tee -a /etc/apt/sources.list.d/sbt.list
    - apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
    - apt-get update -yqq
    - apt-get install -yqq sbt
    - sbt sbtVersion
  script:
    - sbt +clean coverage +test +it:test coverageReport
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - target/scala-2.13/scoverage-report/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-snapshot:
  stage: publish
  tags:
    - wopr
  script:
    - sbt +publish
  only:
    - develop
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

release:
  stage: publish
  image: registry.mdcatapult.io/informatics/docker-images/ci:scala-v1.1.3
  tags:
    - wopr
  script:
    - /scripts/release.sh -b -r develop
  only:
    - master
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/

publish-master:
  stage: publish
  tags:
    - wopr
  script:
    - sbt +publish
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_MESSAGE =~ /^Setting version to.*/
